-- ============================================================================
-- IN WOOD — наповнення цін короба/лиштви/добору та послуг реальними даними
-- Виконати після 0003_quote_builder_schema.sql
-- ============================================================================

insert into public.line_addon_prices (collection, addon_type, item_label, tariff, price) values
  ('etalon', 'korob', 'Телескопічний 80 мм (ETALON)', 'retail', 2945.0),
  ('etalon', 'korob', 'Телескопічний 80 мм (ETALON)', 'dealer', 2061.5),
  ('etalon', 'korob', 'Телескопічний 80 мм (ETALON)', 'distributor', 1767.0),
  ('etalon', 'korob', 'Телескопічний 80 мм (ETALON)', 'builder', 2356.0),
  ('etalon', 'korob', 'Телескопічний 80 мм (ETALON)', 'export', 1717.92),
  ('etalon', 'korob', 'Телескопічний 80 мм (ETALON)', 'epicenter', 2261.76),
  ('etalon', 'korob', 'Телескопічний 100 мм (ETALON)', 'retail', 3926.0),
  ('etalon', 'korob', 'Телескопічний 100 мм (ETALON)', 'dealer', 2748.2),
  ('etalon', 'korob', 'Телескопічний 100 мм (ETALON)', 'distributor', 2355.6),
  ('etalon', 'korob', 'Телескопічний 100 мм (ETALON)', 'builder', 3140.8),
  ('etalon', 'korob', 'Телескопічний 100 мм (ETALON)', 'export', 2290.17),
  ('etalon', 'korob', 'Телескопічний 100 мм (ETALON)', 'epicenter', 3015.17),
  ('etalon', 'korob', 'Телескопічний 120 мм (ETALON)', 'retail', 4308.0),
  ('etalon', 'korob', 'Телескопічний 120 мм (ETALON)', 'dealer', 3015.6),
  ('etalon', 'korob', 'Телескопічний 120 мм (ETALON)', 'distributor', 2584.8),
  ('etalon', 'korob', 'Телескопічний 120 мм (ETALON)', 'builder', 3446.4),
  ('etalon', 'korob', 'Телескопічний 120 мм (ETALON)', 'export', 2513.0),
  ('etalon', 'korob', 'Телескопічний 120 мм (ETALON)', 'epicenter', 3308.54),
  ('etalon', 'korob', 'Компланарний 80 мм (ETALON)', 'retail', 3566.0),
  ('etalon', 'korob', 'Компланарний 80 мм (ETALON)', 'dealer', 2496.2),
  ('etalon', 'korob', 'Компланарний 80 мм (ETALON)', 'distributor', 2139.6),
  ('etalon', 'korob', 'Компланарний 80 мм (ETALON)', 'builder', 2852.8),
  ('etalon', 'korob', 'Компланарний 80 мм (ETALON)', 'export', 2080.17),
  ('etalon', 'korob', 'Компланарний 80 мм (ETALON)', 'epicenter', 2738.69),
  ('etalon', 'korob', 'Компланарний 100 мм (ETALON)', 'retail', 4130.0),
  ('etalon', 'korob', 'Компланарний 100 мм (ETALON)', 'dealer', 2891.0),
  ('etalon', 'korob', 'Компланарний 100 мм (ETALON)', 'distributor', 2478.0),
  ('etalon', 'korob', 'Компланарний 100 мм (ETALON)', 'builder', 3304.0),
  ('etalon', 'korob', 'Компланарний 100 мм (ETALON)', 'export', 2409.17),
  ('etalon', 'korob', 'Компланарний 100 мм (ETALON)', 'epicenter', 3171.84),
  ('etalon', 'korob', 'Компланарний 120 мм (ETALON)', 'retail', 4512.0),
  ('etalon', 'korob', 'Компланарний 120 мм (ETALON)', 'dealer', 3158.4),
  ('etalon', 'korob', 'Компланарний 120 мм (ETALON)', 'distributor', 2707.2),
  ('etalon', 'korob', 'Компланарний 120 мм (ETALON)', 'builder', 3609.6),
  ('etalon', 'korob', 'Компланарний 120 мм (ETALON)', 'export', 2632.0),
  ('etalon', 'korob', 'Компланарний 120 мм (ETALON)', 'epicenter', 3465.22),
  ('etalon', 'korob', 'Телескопічний INSIDE 80 мм (ETALON)', 'retail', 3534.0),
  ('etalon', 'korob', 'Телескопічний INSIDE 80 мм (ETALON)', 'dealer', 2473.8),
  ('etalon', 'korob', 'Телескопічний INSIDE 80 мм (ETALON)', 'distributor', 2120.4),
  ('etalon', 'korob', 'Телескопічний INSIDE 80 мм (ETALON)', 'builder', 2827.2),
  ('etalon', 'korob', 'Телескопічний INSIDE 80 мм (ETALON)', 'export', 2061.5),
  ('etalon', 'korob', 'Телескопічний INSIDE 80 мм (ETALON)', 'epicenter', 2714.11),
  ('etalon', 'korob', 'Телескопічний INSIDE 100 мм (ETALON)', 'retail', 4711.0),
  ('etalon', 'korob', 'Телескопічний INSIDE 100 мм (ETALON)', 'dealer', 3297.7),
  ('etalon', 'korob', 'Телескопічний INSIDE 100 мм (ETALON)', 'distributor', 2826.6),
  ('etalon', 'korob', 'Телескопічний INSIDE 100 мм (ETALON)', 'builder', 3768.8),
  ('etalon', 'korob', 'Телескопічний INSIDE 100 мм (ETALON)', 'export', 2748.08),
  ('etalon', 'korob', 'Телескопічний INSIDE 100 мм (ETALON)', 'epicenter', 3618.05),
  ('etalon', 'korob', 'Телескопічний INSIDE 120 мм (ETALON)', 'retail', 5170.0),
  ('etalon', 'korob', 'Телескопічний INSIDE 120 мм (ETALON)', 'dealer', 3619.0),
  ('etalon', 'korob', 'Телескопічний INSIDE 120 мм (ETALON)', 'distributor', 3102.0),
  ('etalon', 'korob', 'Телескопічний INSIDE 120 мм (ETALON)', 'builder', 4136.0),
  ('etalon', 'korob', 'Телескопічний INSIDE 120 мм (ETALON)', 'export', 3015.83),
  ('etalon', 'korob', 'Телескопічний INSIDE 120 мм (ETALON)', 'epicenter', 3970.56),
  ('etalon', 'korob', 'Компланарний INSIDE 80 мм (ETALON)', 'retail', 4279.0),
  ('etalon', 'korob', 'Компланарний INSIDE 80 мм (ETALON)', 'dealer', 2995.3),
  ('etalon', 'korob', 'Компланарний INSIDE 80 мм (ETALON)', 'distributor', 2567.4),
  ('etalon', 'korob', 'Компланарний INSIDE 80 мм (ETALON)', 'builder', 3423.2),
  ('etalon', 'korob', 'Компланарний INSIDE 80 мм (ETALON)', 'export', 2496.08),
  ('etalon', 'korob', 'Компланарний INSIDE 80 мм (ETALON)', 'epicenter', 3286.27),
  ('etalon', 'korob', 'Компланарний INSIDE 100 мм (ETALON)', 'retail', 4956.0),
  ('etalon', 'korob', 'Компланарний INSIDE 100 мм (ETALON)', 'dealer', 3469.2),
  ('etalon', 'korob', 'Компланарний INSIDE 100 мм (ETALON)', 'distributor', 2973.6),
  ('etalon', 'korob', 'Компланарний INSIDE 100 мм (ETALON)', 'builder', 3964.8),
  ('etalon', 'korob', 'Компланарний INSIDE 100 мм (ETALON)', 'export', 2891.0),
  ('etalon', 'korob', 'Компланарний INSIDE 100 мм (ETALON)', 'epicenter', 3806.21),
  ('etalon', 'korob', 'Компланарний INSIDE 120 мм (ETALON)', 'retail', 5414.4),
  ('etalon', 'korob', 'Компланарний INSIDE 120 мм (ETALON)', 'dealer', 3790.08),
  ('etalon', 'korob', 'Компланарний INSIDE 120 мм (ETALON)', 'distributor', 3248.64),
  ('etalon', 'korob', 'Компланарний INSIDE 120 мм (ETALON)', 'builder', 4331.52),
  ('etalon', 'korob', 'Компланарний INSIDE 120 мм (ETALON)', 'export', 3158.4),
  ('etalon', 'korob', 'Компланарний INSIDE 120 мм (ETALON)', 'epicenter', 4158.26),
  ('etalon', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'retail', 8424.0),
  ('etalon', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'dealer', 5896.8),
  ('etalon', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'distributor', 5054.4),
  ('etalon', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'builder', 6739.2),
  ('etalon', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'export', 4914.0),
  ('etalon', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'epicenter', 6469.63),
  ('etalon', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'retail', 9752.0),
  ('etalon', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'dealer', 6826.4),
  ('etalon', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'distributor', 5851.2),
  ('etalon', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'builder', 7801.6),
  ('etalon', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'export', 5688.67),
  ('etalon', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'epicenter', 7489.54),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (ETALON)', 'retail', 1278.0),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (ETALON)', 'dealer', 894.6),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (ETALON)', 'distributor', 766.8),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (ETALON)', 'builder', 1022.4),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (ETALON)', 'export', 745.5),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (ETALON)', 'epicenter', 981.5),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (ETALON)', 'retail', 1541.0),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (ETALON)', 'dealer', 1078.7),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (ETALON)', 'distributor', 924.6),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (ETALON)', 'builder', 1232.8),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (ETALON)', 'export', 898.92),
  ('etalon', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (ETALON)', 'epicenter', 1183.49),
  ('etalon', 'lishtva', 'Компланарна 80 мм (ETALON)', 'retail', 1636.0),
  ('etalon', 'lishtva', 'Компланарна 80 мм (ETALON)', 'dealer', 1145.2),
  ('etalon', 'lishtva', 'Компланарна 80 мм (ETALON)', 'distributor', 981.6),
  ('etalon', 'lishtva', 'Компланарна 80 мм (ETALON)', 'builder', 1308.8),
  ('etalon', 'lishtva', 'Компланарна 80 мм (ETALON)', 'export', 954.33),
  ('etalon', 'lishtva', 'Компланарна 80 мм (ETALON)', 'epicenter', 1256.45),
  ('etalon', 'dobir', 'Телескопічний 100 мм (ETALON)', 'retail', 1126.0),
  ('etalon', 'dobir', 'Телескопічний 100 мм (ETALON)', 'dealer', 788.2),
  ('etalon', 'dobir', 'Телескопічний 100 мм (ETALON)', 'distributor', 675.6),
  ('etalon', 'dobir', 'Телескопічний 100 мм (ETALON)', 'builder', 900.8),
  ('etalon', 'dobir', 'Телескопічний 100 мм (ETALON)', 'export', 656.83),
  ('etalon', 'dobir', 'Телескопічний 100 мм (ETALON)', 'epicenter', 864.77),
  ('etalon', 'dobir', 'Телескопічний 150 мм (ETALON)', 'retail', 1470.0),
  ('etalon', 'dobir', 'Телескопічний 150 мм (ETALON)', 'dealer', 1029.0),
  ('etalon', 'dobir', 'Телескопічний 150 мм (ETALON)', 'distributor', 882.0),
  ('etalon', 'dobir', 'Телескопічний 150 мм (ETALON)', 'builder', 1176.0),
  ('etalon', 'dobir', 'Телескопічний 150 мм (ETALON)', 'export', 857.5),
  ('etalon', 'dobir', 'Телескопічний 150 мм (ETALON)', 'epicenter', 1128.96),
  ('etalon', 'dobir', 'Телескопічний 200 мм (ETALON)', 'retail', 2155.0),
  ('etalon', 'dobir', 'Телескопічний 200 мм (ETALON)', 'dealer', 1508.5),
  ('etalon', 'dobir', 'Телескопічний 200 мм (ETALON)', 'distributor', 1293.0),
  ('etalon', 'dobir', 'Телескопічний 200 мм (ETALON)', 'builder', 1724.0),
  ('etalon', 'dobir', 'Телескопічний 200 мм (ETALON)', 'export', 1257.08),
  ('etalon', 'dobir', 'Телескопічний 200 мм (ETALON)', 'epicenter', 1655.04),
  ('nominal', 'korob', 'Телескопічний 80 мм (NOMINAL)', 'retail', 2646.0),
  ('nominal', 'korob', 'Телескопічний 80 мм (NOMINAL)', 'dealer', 1852.2),
  ('nominal', 'korob', 'Телескопічний 80 мм (NOMINAL)', 'distributor', 1587.6),
  ('nominal', 'korob', 'Телескопічний 80 мм (NOMINAL)', 'builder', 2116.8),
  ('nominal', 'korob', 'Телескопічний 80 мм (NOMINAL)', 'export', 1543.5),
  ('nominal', 'korob', 'Телескопічний 80 мм (NOMINAL)', 'epicenter', 2032.13),
  ('nominal', 'korob', 'Телескопічний 100 мм (NOMINAL)', 'retail', 3753.0),
  ('nominal', 'korob', 'Телескопічний 100 мм (NOMINAL)', 'dealer', 2627.1),
  ('nominal', 'korob', 'Телескопічний 100 мм (NOMINAL)', 'distributor', 2251.8),
  ('nominal', 'korob', 'Телескопічний 100 мм (NOMINAL)', 'builder', 3002.4),
  ('nominal', 'korob', 'Телескопічний 100 мм (NOMINAL)', 'export', 2189.25),
  ('nominal', 'korob', 'Телескопічний 100 мм (NOMINAL)', 'epicenter', 2882.3),
  ('nominal', 'korob', 'Телескопічний 120 мм (NOMINAL)', 'retail', 3944.0),
  ('nominal', 'korob', 'Телескопічний 120 мм (NOMINAL)', 'dealer', 2760.8),
  ('nominal', 'korob', 'Телескопічний 120 мм (NOMINAL)', 'distributor', 2366.4),
  ('nominal', 'korob', 'Телескопічний 120 мм (NOMINAL)', 'builder', 3155.2),
  ('nominal', 'korob', 'Телескопічний 120 мм (NOMINAL)', 'export', 2300.67),
  ('nominal', 'korob', 'Телескопічний 120 мм (NOMINAL)', 'epicenter', 3028.99),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (NOMINAL)', 'retail', 1027.0),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (NOMINAL)', 'dealer', 718.9),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (NOMINAL)', 'distributor', 616.2),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (NOMINAL)', 'builder', 821.6),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (NOMINAL)', 'export', 599.08),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (NOMINAL)', 'epicenter', 788.74),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (NOMINAL)', 'retail', 1315.0),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (NOMINAL)', 'dealer', 920.5),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (NOMINAL)', 'distributor', 789.0),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (NOMINAL)', 'builder', 1052.0),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (NOMINAL)', 'export', 767.08),
  ('nominal', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (NOMINAL)', 'epicenter', 1009.92),
  ('nominal', 'dobir', 'Телескопічний 100 мм (NOMINAL)', 'retail', 1012.0),
  ('nominal', 'dobir', 'Телескопічний 100 мм (NOMINAL)', 'dealer', 708.4),
  ('nominal', 'dobir', 'Телескопічний 100 мм (NOMINAL)', 'distributor', 607.2),
  ('nominal', 'dobir', 'Телескопічний 100 мм (NOMINAL)', 'builder', 809.6),
  ('nominal', 'dobir', 'Телескопічний 100 мм (NOMINAL)', 'export', 590.33),
  ('nominal', 'dobir', 'Телескопічний 100 мм (NOMINAL)', 'epicenter', 777.22),
  ('nominal', 'dobir', 'Телескопічний 150 мм (NOMINAL)', 'retail', 1336.0),
  ('nominal', 'dobir', 'Телескопічний 150 мм (NOMINAL)', 'dealer', 935.2),
  ('nominal', 'dobir', 'Телескопічний 150 мм (NOMINAL)', 'distributor', 801.6),
  ('nominal', 'dobir', 'Телескопічний 150 мм (NOMINAL)', 'builder', 1068.8),
  ('nominal', 'dobir', 'Телескопічний 150 мм (NOMINAL)', 'export', 779.33),
  ('nominal', 'dobir', 'Телескопічний 150 мм (NOMINAL)', 'epicenter', 1026.05),
  ('nominal', 'dobir', 'Телескопічний 200 мм (NOMINAL)', 'retail', 1920.0),
  ('nominal', 'dobir', 'Телескопічний 200 мм (NOMINAL)', 'dealer', 1344.0),
  ('nominal', 'dobir', 'Телескопічний 200 мм (NOMINAL)', 'distributor', 1152.0),
  ('nominal', 'dobir', 'Телескопічний 200 мм (NOMINAL)', 'builder', 1536.0),
  ('nominal', 'dobir', 'Телескопічний 200 мм (NOMINAL)', 'export', 1120.0),
  ('nominal', 'dobir', 'Телескопічний 200 мм (NOMINAL)', 'epicenter', 1474.56),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI)', 'retail', 2646.0),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI)', 'dealer', 1852.2),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI)', 'distributor', 1587.6),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI)', 'builder', 2116.8),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI)', 'export', 1543.5),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI)', 'epicenter', 2032.13),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI)', 'retail', 3753.0),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI)', 'dealer', 2627.1),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI)', 'distributor', 2251.8),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI)', 'builder', 3002.4),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI)', 'export', 2189.25),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI)', 'epicenter', 2882.3),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI)', 'retail', 3944.0),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI)', 'dealer', 2760.8),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI)', 'distributor', 2366.4),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI)', 'builder', 3155.2),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI)', 'export', 2300.67),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI)', 'epicenter', 3028.99),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI, RAL/NCS)', 'retail', 4374.0),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI, RAL/NCS)', 'dealer', 3061.8),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI, RAL/NCS)', 'distributor', 2624.4),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI, RAL/NCS)', 'builder', 3499.2),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI, RAL/NCS)', 'export', 2551.5),
  ('frezzatti', 'korob', 'Телескопічний 80 мм (FREZZATTI, RAL/NCS)', 'epicenter', 3359.23),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'retail', 5018.0),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'dealer', 3512.6),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'distributor', 3010.8),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'builder', 4014.4),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'export', 2927.17),
  ('frezzatti', 'korob', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'epicenter', 3853.82),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI, RAL/NCS)', 'retail', 5312.0),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI, RAL/NCS)', 'dealer', 3718.4),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI, RAL/NCS)', 'distributor', 3187.2),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI, RAL/NCS)', 'builder', 4249.6),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI, RAL/NCS)', 'export', 3098.67),
  ('frezzatti', 'korob', 'Телескопічний 120 мм (FREZZATTI, RAL/NCS)', 'epicenter', 4079.62),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI)', 'retail', 1027.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI)', 'dealer', 718.9),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI)', 'distributor', 616.2),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI)', 'builder', 821.6),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI)', 'export', 599.08),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI)', 'epicenter', 788.74),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (FREZZATTI)', 'retail', 1315.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (FREZZATTI)', 'dealer', 920.5),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (FREZZATTI)', 'distributor', 789.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (FREZZATTI)', 'builder', 1052.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (FREZZATTI)', 'export', 767.08),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (FREZZATTI)', 'epicenter', 1009.92),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI, RAL/NCS)', 'retail', 1836.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI, RAL/NCS)', 'dealer', 1285.2),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI, RAL/NCS)', 'distributor', 1101.6),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI, RAL/NCS)', 'builder', 1468.8),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI, RAL/NCS)', 'export', 1071.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (FREZZATTI, RAL/NCS)', 'epicenter', 1410.05),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (FREZZATTI, RAL/NCS)', 'retail', 2042.0),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (FREZZATTI, RAL/NCS)', 'dealer', 1429.4),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (FREZZATTI, RAL/NCS)', 'distributor', 1225.2),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (FREZZATTI, RAL/NCS)', 'builder', 1633.6),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (FREZZATTI, RAL/NCS)', 'export', 1191.17),
  ('frezzatti', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (FREZZATTI, RAL/NCS)', 'epicenter', 1568.26),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI)', 'retail', 1012.0),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI)', 'dealer', 708.4),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI)', 'distributor', 607.2),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI)', 'builder', 809.6),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI)', 'export', 590.33),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI)', 'epicenter', 777.22),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI)', 'retail', 1336.0),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI)', 'dealer', 935.2),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI)', 'distributor', 801.6),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI)', 'builder', 1068.8),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI)', 'export', 779.33),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI)', 'epicenter', 1026.05),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI)', 'retail', 1920.0),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI)', 'dealer', 1344.0),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI)', 'distributor', 1152.0),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI)', 'builder', 1536.0),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI)', 'export', 1120.0),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI)', 'epicenter', 1474.56),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'retail', 1808.0),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'dealer', 1265.6),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'distributor', 1084.8),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'builder', 1446.4),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'export', 1054.67),
  ('frezzatti', 'dobir', 'Телескопічний 100 мм (FREZZATTI, RAL/NCS)', 'epicenter', 1388.54),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI, RAL/NCS)', 'retail', 2038.0),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI, RAL/NCS)', 'dealer', 1426.6),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI, RAL/NCS)', 'distributor', 1222.8),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI, RAL/NCS)', 'builder', 1630.4),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI, RAL/NCS)', 'export', 1188.83),
  ('frezzatti', 'dobir', 'Телескопічний 150 мм (FREZZATTI, RAL/NCS)', 'epicenter', 1565.18),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI, RAL/NCS)', 'retail', 2403.0),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI, RAL/NCS)', 'dealer', 1682.1),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI, RAL/NCS)', 'distributor', 1441.8),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI, RAL/NCS)', 'builder', 1922.4),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI, RAL/NCS)', 'export', 1401.75),
  ('frezzatti', 'dobir', 'Телескопічний 200 мм (FREZZATTI, RAL/NCS)', 'epicenter', 1845.5),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO)', 'retail', 2945.0),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO)', 'dealer', 2061.5),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO)', 'distributor', 1767.0),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO)', 'builder', 2356.0),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO)', 'export', 1717.92),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO)', 'epicenter', 2261.76),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO)', 'retail', 3926.0),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO)', 'dealer', 2748.2),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO)', 'distributor', 2355.6),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO)', 'builder', 3140.8),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO)', 'export', 2290.17),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO)', 'epicenter', 3015.17),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO)', 'retail', 4308.0),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO)', 'dealer', 3015.6),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO)', 'distributor', 2584.8),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO)', 'builder', 3446.4),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO)', 'export', 2513.0),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO)', 'epicenter', 3308.54),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO)', 'retail', 3566.0),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO)', 'dealer', 2496.2),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO)', 'distributor', 2139.6),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO)', 'builder', 2852.8),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO)', 'export', 2080.17),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO)', 'epicenter', 2738.69),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO)', 'retail', 4130.0),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO)', 'dealer', 2891.0),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO)', 'distributor', 2478.0),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO)', 'builder', 3304.0),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO)', 'export', 2409.17),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO)', 'epicenter', 3171.84),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO)', 'retail', 4512.0),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO)', 'dealer', 3158.4),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO)', 'distributor', 2707.2),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO)', 'builder', 3609.6),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO)', 'export', 2632.0),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO)', 'epicenter', 3465.22),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO, RAL/NCS)', 'retail', 4374.0),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO, RAL/NCS)', 'dealer', 3061.8),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO, RAL/NCS)', 'distributor', 2624.4),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO, RAL/NCS)', 'builder', 3499.2),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO, RAL/NCS)', 'export', 2551.5),
  ('perfetto', 'korob', 'Телескопічний 80 мм (PERFETTO, RAL/NCS)', 'epicenter', 3359.23),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'retail', 5018.0),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'dealer', 3512.6),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'distributor', 3010.8),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'builder', 4014.4),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'export', 2927.17),
  ('perfetto', 'korob', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'epicenter', 3853.82),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO, RAL/NCS)', 'retail', 5312.0),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO, RAL/NCS)', 'dealer', 3718.4),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO, RAL/NCS)', 'distributor', 3187.2),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO, RAL/NCS)', 'builder', 4249.6),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO, RAL/NCS)', 'export', 3098.67),
  ('perfetto', 'korob', 'Телескопічний 120 мм (PERFETTO, RAL/NCS)', 'epicenter', 4079.62),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO, RAL/NCS)', 'retail', 4374.0),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO, RAL/NCS)', 'dealer', 3061.8),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO, RAL/NCS)', 'distributor', 2624.4),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO, RAL/NCS)', 'builder', 3499.2),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO, RAL/NCS)', 'export', 2551.5),
  ('perfetto', 'korob', 'Компланарний 80 мм (PERFETTO, RAL/NCS)', 'epicenter', 3359.23),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO, RAL/NCS)', 'retail', 5154.0),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO, RAL/NCS)', 'dealer', 3607.8),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO, RAL/NCS)', 'distributor', 3092.4),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO, RAL/NCS)', 'builder', 4123.2),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO, RAL/NCS)', 'export', 3006.5),
  ('perfetto', 'korob', 'Компланарний 100 мм (PERFETTO, RAL/NCS)', 'epicenter', 3958.27),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO, RAL/NCS)', 'retail', 5720.0),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO, RAL/NCS)', 'dealer', 4004.0),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO, RAL/NCS)', 'distributor', 3432.0),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO, RAL/NCS)', 'builder', 4576.0),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO, RAL/NCS)', 'export', 3336.67),
  ('perfetto', 'korob', 'Компланарний 120 мм (PERFETTO, RAL/NCS)', 'epicenter', 4392.96),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO)', 'retail', 1278.0),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO)', 'dealer', 894.6),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO)', 'distributor', 766.8),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO)', 'builder', 1022.4),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO)', 'export', 745.5),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO)', 'epicenter', 981.5),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (PERFETTO)', 'retail', 1541.0),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (PERFETTO)', 'dealer', 1078.7),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (PERFETTO)', 'distributor', 924.6),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (PERFETTO)', 'builder', 1232.8),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (PERFETTO)', 'export', 898.92),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм) (PERFETTO)', 'epicenter', 1183.49),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO)', 'retail', 1636.0),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO)', 'dealer', 1145.2),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO)', 'distributor', 981.6),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO)', 'builder', 1308.8),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO)', 'export', 954.33),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO)', 'epicenter', 1256.45),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO, RAL/NCS)', 'retail', 1836.0),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO, RAL/NCS)', 'dealer', 1285.2),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO, RAL/NCS)', 'distributor', 1101.6),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO, RAL/NCS)', 'builder', 1468.8),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO, RAL/NCS)', 'export', 1071.0),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (PERFETTO, RAL/NCS)', 'epicenter', 1410.05),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (PERFETTO, RAL/NCS)', 'retail', 2042.0),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (PERFETTO, RAL/NCS)', 'dealer', 1429.4),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (PERFETTO, RAL/NCS)', 'distributor', 1225.2),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (PERFETTO, RAL/NCS)', 'builder', 1633.6),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (PERFETTO, RAL/NCS)', 'export', 1191.17),
  ('perfetto', 'lishtva', 'Телескопічна 80 мм (крило 40 мм, +RAL/NCS) (PERFETTO, RAL/NCS)', 'epicenter', 1568.26),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO, RAL/NCS)', 'retail', 2250.0),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO, RAL/NCS)', 'dealer', 1575.0),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO, RAL/NCS)', 'distributor', 1350.0),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO, RAL/NCS)', 'builder', 1800.0),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO, RAL/NCS)', 'export', 1312.5),
  ('perfetto', 'lishtva', 'Компланарна 80 мм (PERFETTO, RAL/NCS)', 'epicenter', 1728.0),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO)', 'retail', 1126.0),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO)', 'dealer', 788.2),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO)', 'distributor', 675.6),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO)', 'builder', 900.8),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO)', 'export', 656.83),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO)', 'epicenter', 864.77),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO)', 'retail', 1470.0),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO)', 'dealer', 1029.0),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO)', 'distributor', 882.0),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO)', 'builder', 1176.0),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO)', 'export', 857.5),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO)', 'epicenter', 1128.96),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO)', 'retail', 2155.0),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO)', 'dealer', 1508.5),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO)', 'distributor', 1293.0),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO)', 'builder', 1724.0),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO)', 'export', 1257.08),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO)', 'epicenter', 1655.04),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'retail', 1808.0),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'dealer', 1265.6),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'distributor', 1084.8),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'builder', 1446.4),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'export', 1054.67),
  ('perfetto', 'dobir', 'Телескопічний 100 мм (PERFETTO, RAL/NCS)', 'epicenter', 1388.54),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO, RAL/NCS)', 'retail', 2038.0),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO, RAL/NCS)', 'dealer', 1426.6),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO, RAL/NCS)', 'distributor', 1222.8),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO, RAL/NCS)', 'builder', 1630.4),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO, RAL/NCS)', 'export', 1188.83),
  ('perfetto', 'dobir', 'Телескопічний 150 мм (PERFETTO, RAL/NCS)', 'epicenter', 1565.18),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO, RAL/NCS)', 'retail', 2403.0),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO, RAL/NCS)', 'dealer', 1682.1),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO, RAL/NCS)', 'distributor', 1441.8),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO, RAL/NCS)', 'builder', 1922.4),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO, RAL/NCS)', 'export', 1401.75),
  ('perfetto', 'dobir', 'Телескопічний 200 мм (PERFETTO, RAL/NCS)', 'epicenter', 1845.5),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'retail', 8424.0),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'dealer', 5896.8),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'distributor', 5054.4),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'builder', 6739.2),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'export', 4914.0),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу STANDART (під шпатлівку)', 'epicenter', 6469.63),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'retail', 9752.0),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'dealer', 6826.4),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'distributor', 5851.2),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'builder', 7801.6),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'export', 5688.67),
  ('hidden-doors', 'korob', 'Коробка прихованого монтажу LUX (під панелі)', 'epicenter', 7489.54),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, 40 мм', 'retail', 2788.0),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, 40 мм', 'dealer', 1951.6),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, 40 мм', 'distributor', 1672.8),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, 40 мм', 'builder', 2230.4),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, 40 мм', 'export', 1626.33),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, 40 мм', 'epicenter', 2141.18),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, Inside, 56 мм', 'retail', 5133.0),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, Inside, 56 мм', 'dealer', 3593.1),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, Inside, 56 мм', 'distributor', 3079.8),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, Inside, 56 мм', 'builder', 4106.4),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, Inside, 56 мм', 'export', 2994.25),
  ('hidden-doors', 'lishtva', 'Система алюм. профілів для торцювання, Inside, 56 мм', 'epicenter', 3942.14)
on conflict (collection, addon_type, item_label, tariff) do update set price = excluded.price;

insert into public.service_tariff_prices (service_key, tariff, price) values
  ('VRIZKA_FULL_PRICE', 'retail', 600.0),
  ('VRIZKA_FULL_PRICE', 'dealer', 420.0),
  ('VRIZKA_FULL_PRICE', 'distributor', 360.0),
  ('VRIZKA_FULL_PRICE', 'builder', 480.0),
  ('VRIZKA_FULL_PRICE', 'export', 350.0),
  ('VRIZKA_FULL_PRICE', 'epicenter', 460.8),
  ('VRIZKA_LOCK_PRICE', 'retail', 300.0),
  ('VRIZKA_LOCK_PRICE', 'dealer', 210.0),
  ('VRIZKA_LOCK_PRICE', 'distributor', 180.0),
  ('VRIZKA_LOCK_PRICE', 'builder', 240.0),
  ('VRIZKA_LOCK_PRICE', 'export', 175.0),
  ('VRIZKA_LOCK_PRICE', 'epicenter', 230.4),
  ('VRIZKA_FULL_PRICE_ALU', 'retail', 680.0),
  ('VRIZKA_FULL_PRICE_ALU', 'dealer', 476.0),
  ('VRIZKA_FULL_PRICE_ALU', 'distributor', 408.0),
  ('VRIZKA_FULL_PRICE_ALU', 'builder', 544.0),
  ('VRIZKA_FULL_PRICE_ALU', 'export', 396.67),
  ('VRIZKA_FULL_PRICE_ALU', 'epicenter', 522.24),
  ('VRIZKA_LOCK_PRICE_ALU', 'retail', 340.0),
  ('VRIZKA_LOCK_PRICE_ALU', 'dealer', 238.0),
  ('VRIZKA_LOCK_PRICE_ALU', 'distributor', 204.0),
  ('VRIZKA_LOCK_PRICE_ALU', 'builder', 272.0),
  ('VRIZKA_LOCK_PRICE_ALU', 'export', 198.33),
  ('VRIZKA_LOCK_PRICE_ALU', 'epicenter', 261.12),
  ('SHUMO_PRICE', 'retail', 1200.0),
  ('SHUMO_PRICE', 'dealer', 840.0),
  ('SHUMO_PRICE', 'distributor', 720.0),
  ('SHUMO_PRICE', 'builder', 960.0),
  ('SHUMO_PRICE', 'export', 700.0),
  ('SHUMO_PRICE', 'epicenter', 921.6),
  ('ALUM_PAINT_PRICE', 'retail', 600.0),
  ('ALUM_PAINT_PRICE', 'dealer', 420.0),
  ('ALUM_PAINT_PRICE', 'distributor', 360.0),
  ('ALUM_PAINT_PRICE', 'builder', 480.0),
  ('ALUM_PAINT_PRICE', 'export', 350.0),
  ('ALUM_PAINT_PRICE', 'epicenter', 460.8),
  ('PAINT_KOROB_RAL_PRICE', 'retail', 830.0),
  ('PAINT_KOROB_RAL_PRICE', 'dealer', 581.0),
  ('PAINT_KOROB_RAL_PRICE', 'distributor', 498.0),
  ('PAINT_KOROB_RAL_PRICE', 'builder', 664.0),
  ('PAINT_KOROB_RAL_PRICE', 'export', 484.17),
  ('PAINT_KOROB_RAL_PRICE', 'epicenter', 637.44)
on conflict (service_key, tariff) do update set price = excluded.price;
