-- ============================================================================
-- IN WOOD -- розширює фото фурнітури MVM з 285 до 421 позиції (з 485).
-- Товари одного виробу в різних кольорах/оздобленнях (напр. HE-120 AB/CP/MA/PN)
-- у прайс-файлі постачальника мають ОДНЕ спільне фото на групу -- застосовано
-- те саме фото до всіх кольорів групи (чесно, не вигадано -- це так у джерелі:
-- назва товару в екселі теж пишеться один раз на групу кольорів).
-- Виконати цілком у Supabase Dashboard SQL Editor (після 0019).
-- ============================================================================

update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/1162-l-18-b-p-t5.png' where brand = 'MVM' and article = '1162 L-1.8 Б/П T5';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/1162-l-36-b-p-t5.png' where brand = 'MVM' and article = '1162 L-3.6 Б/П T5';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-1209-sn-cp.png' where brand = 'MVM' and article = 'A-1209 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-1210-85-ab.png' where brand = 'MVM' and article = 'A-1210-85 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-1210-85-sn-cp.png' where brand = 'MVM' and article = 'A-1210-85 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-1220-sn-cp.png' where brand = 'MVM' and article = 'A-1220 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-1355-sn-cp.png' where brand = 'MVM' and article = 'A-1355 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2004-ab.png' where brand = 'MVM' and article = 'A-2004 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2004-ma.png' where brand = 'MVM' and article = 'A-2004 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2004-mc.png' where brand = 'MVM' and article = 'A-2004 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2004-sn-cp.png' where brand = 'MVM' and article = 'A-2004 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2005-ab.png' where brand = 'MVM' and article = 'A-2005 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2005-sn-cp.png' where brand = 'MVM' and article = 'A-2005 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2006-ma.png' where brand = 'MVM' and article = 'A-2006 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2006-sn-cp.png' where brand = 'MVM' and article = 'A-2006 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2008-black.png' where brand = 'MVM' and article = 'A-2008 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2008-sn-cp.png' where brand = 'MVM' and article = 'A-2008 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2009-ab.png' where brand = 'MVM' and article = 'A-2009 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2010-e20-black.png' where brand = 'MVM' and article = 'A-2010/E20 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2010-e20-ma.png' where brand = 'MVM' and article = 'A-2010/E20 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2010-e20-sn.png' where brand = 'MVM' and article = 'A-2010/E20 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2017-black.png' where brand = 'MVM' and article = 'A-2017 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2018-black.png' where brand = 'MVM' and article = 'A-2018 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2018-mc.png' where brand = 'MVM' and article = 'A-2018 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2018-sn.png' where brand = 'MVM' and article = 'A-2018 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2020-black.png' where brand = 'MVM' and article = 'A-2020 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2020-ma.png' where brand = 'MVM' and article = 'A-2020 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2021-black.png' where brand = 'MVM' and article = 'A-2021 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2021-mc.png' where brand = 'MVM' and article = 'A-2021 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2021-sn.png' where brand = 'MVM' and article = 'A-2021 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2025-mn.png' where brand = 'MVM' and article = 'A-2025 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2028-black.png' where brand = 'MVM' and article = 'A-2028 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2028-sc.png' where brand = 'MVM' and article = 'A-2028 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2029-black.png' where brand = 'MVM' and article = 'A-2029 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2029-mn.png' where brand = 'MVM' and article = 'A-2029 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a-2030-black.png' where brand = 'MVM' and article = 'A-2030 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e30-30-cp.png' where brand = 'MVM' and article = 'A5E30/30 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e30-30-pb.png' where brand = 'MVM' and article = 'A5E30/30 PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e30-30t-cp.png' where brand = 'MVM' and article = 'A5E30/30T CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e30-30t-pb.png' where brand = 'MVM' and article = 'A5E30/30T PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e35-35-cp.png' where brand = 'MVM' and article = 'A5E35/35 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e35-35-pb.png' where brand = 'MVM' and article = 'A5E35/35 PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e35-35t-cp.png' where brand = 'MVM' and article = 'A5E35/35T CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a5e35-35t-pb.png' where brand = 'MVM' and article = 'A5E35/35T PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30-black.png' where brand = 'MVM' and article = 'A6P30/30 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30-cp.png' where brand = 'MVM' and article = 'A6P30/30 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30-mc.png' where brand = 'MVM' and article = 'A6P30/30 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30-pb.png' where brand = 'MVM' and article = 'A6P30/30 PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30t-black.png' where brand = 'MVM' and article = 'A6P30/30T BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30t-cp.png' where brand = 'MVM' and article = 'A6P30/30T CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30t-mc.png' where brand = 'MVM' and article = 'A6P30/30T MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-30t-pb.png' where brand = 'MVM' and article = 'A6P30/30T PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30-40-cp.png' where brand = 'MVM' and article = 'A6P30/40 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p30t-40-cp.png' where brand = 'MVM' and article = 'A6P30T/40 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p35-35-cp.png' where brand = 'MVM' and article = 'A6P35/35 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p35-35-pb.png' where brand = 'MVM' and article = 'A6P35/35 PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p35-35t-cp.png' where brand = 'MVM' and article = 'A6P35/35T CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p35-35t-pb.png' where brand = 'MVM' and article = 'A6P35/35T PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p35-55-cp.png' where brand = 'MVM' and article = 'A6P35/55 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p35t-55-cp.png' where brand = 'MVM' and article = 'A6P35T/55 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p40-40-cp.png' where brand = 'MVM' and article = 'A6P40/40 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p40-40t-cp.png' where brand = 'MVM' and article = 'A6P40/40T CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p45-45-cp.png' where brand = 'MVM' and article = 'A6P45/45 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/a6p45-45t-cp.png' where brand = 'MVM' and article = 'A6P45/45T CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/an-140-3d-mc.png' where brand = 'MVM' and article = 'AN 140 3D MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/an-172-3d-black.png' where brand = 'MVM' and article = 'AN 172 3D BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/an-172-3d-mc.png' where brand = 'MVM' and article = 'AN 172 3D MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/b-100-ab.png' where brand = 'MVM' and article = 'B-100 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/b-100-mc.png' where brand = 'MVM' and article = 'B-100 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/c-140-ab.png' where brand = 'MVM' and article = 'C-140 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/c-140-black.png' where brand = 'MVM' and article = 'C-140 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/c-140-ma.png' where brand = 'MVM' and article = 'C-140 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/c-140-sn.png' where brand = 'MVM' and article = 'C-140 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-30-40-5k.jpg' where brand = 'MVM' and article = 'D15 N 30/40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-35-35-5k.jpg' where brand = 'MVM' and article = 'D15 N 35/35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-35-45-5k.jpg' where brand = 'MVM' and article = 'D15 N 35/45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-40-40-5k.jpg' where brand = 'MVM' and article = 'D15 N 40/40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-40-50-5k.jpg' where brand = 'MVM' and article = 'D15 N 40/50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-45-45-5k.jpg' where brand = 'MVM' and article = 'D15 N 45/45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d15-n-50-50-5k.jpg' where brand = 'MVM' and article = 'D15 N 50/50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-mm-30-30-5k.jpg' where brand = 'MVM' and article = 'D6PS MM 30/30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-mm-35-35-5k.jpg' where brand = 'MVM' and article = 'D6PS MM 35/35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-30-30-5k.jpg' where brand = 'MVM' and article = 'D6PS N 30/30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-30-40-5k.jpg' where brand = 'MVM' and article = 'D6PS N 30/40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-30-50-5k.jpg' where brand = 'MVM' and article = 'D6PS N 30/50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-30-60-5k.jpg' where brand = 'MVM' and article = 'D6PS N 30/60 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-35-35-5k.jpg' where brand = 'MVM' and article = 'D6PS N 35/35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-35-45-5k.jpg' where brand = 'MVM' and article = 'D6PS N 35/45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-35-55-5k.jpg' where brand = 'MVM' and article = 'D6PS N 35/55 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-40-40-5k.jpg' where brand = 'MVM' and article = 'D6PS N 40/40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-40-50-5k.jpg' where brand = 'MVM' and article = 'D6PS N 40/50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-45-45-5k.jpg' where brand = 'MVM' and article = 'D6PS N 45/45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-50-50-5k.jpg' where brand = 'MVM' and article = 'D6PS N 50/50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/d6ps-n-55-55-5k.jpg' where brand = 'MVM' and article = 'D6PS N 55/55 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-d-14x12-brown.png' where brand = 'MVM' and article = 'DS-D 14x12 BROWN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-d-14x12-gray.png' where brand = 'MVM' and article = 'DS-D 14x12 GRAY';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-d-14x12-white.png' where brand = 'MVM' and article = 'DS-D 14x12 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-d-9x75-brown.png' where brand = 'MVM' and article = 'DS-D 9x7,5 BROWN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-d-9x75-gray.png' where brand = 'MVM' and article = 'DS-D 9x7,5 GRAY';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-d-9x75-white.png' where brand = 'MVM' and article = 'DS-D 9x7,5 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-e-9x4-brown.png' where brand = 'MVM' and article = 'DS-E 9x4 BROWN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-e-9x4-gray.png' where brand = 'MVM' and article = 'DS-E 9x4 GRAY';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-e-9x4-white.png' where brand = 'MVM' and article = 'DS-E 9x4 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-i-9x2-brown.png' where brand = 'MVM' and article = 'DS-I 9x2 BROWN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-i-9x2-gray.png' where brand = 'MVM' and article = 'DS-I 9x2 GRAY';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ds-i-9x2-white.png' where brand = 'MVM' and article = 'DS-I 9x2 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/dv35-55-16-mc.png' where brand = 'MVM' and article = 'DV35-55/16 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/dv35-55-16-sb.png' where brand = 'MVM' and article = 'DV35-55/16 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/dv50-90-16-mc.png' where brand = 'MVM' and article = 'DV50-90/16 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/dv50-90-16-sb.png' where brand = 'MVM' and article = 'DV50-90/16 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e1-ma.png' where brand = 'MVM' and article = 'E1 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e11-ss.png' where brand = 'MVM' and article = 'E11 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e12-black.png' where brand = 'MVM' and article = 'E12 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e12-ss.png' where brand = 'MVM' and article = 'E12 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e16-black.png' where brand = 'MVM' and article = 'E16 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e19-black.png' where brand = 'MVM' and article = 'E19 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e19-ma.png' where brand = 'MVM' and article = 'E19 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e19-mn.png' where brand = 'MVM' and article = 'E19 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e19-sc.png' where brand = 'MVM' and article = 'E19 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e19-sn.png' where brand = 'MVM' and article = 'E19 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-black.png' where brand = 'MVM' and article = 'E20 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-ma.png' where brand = 'MVM' and article = 'E20 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-mc.png' where brand = 'MVM' and article = 'E20 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-mn.png' where brand = 'MVM' and article = 'E20 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-sbn.png' where brand = 'MVM' and article = 'E20 SBN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-sc.png' where brand = 'MVM' and article = 'E20 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e20-sn.png' where brand = 'MVM' and article = 'E20 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e3-ab.png' where brand = 'MVM' and article = 'E3 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e3-sn-cp.png' where brand = 'MVM' and article = 'E3 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e4-black.png' where brand = 'MVM' and article = 'E4 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e4-mc.png' where brand = 'MVM' and article = 'E4 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e5-ab.png' where brand = 'MVM' and article = 'E5 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e5-sn-cp.png' where brand = 'MVM' and article = 'E5 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e50-mm-30-30.jpeg' where brand = 'MVM' and article = 'E50 MM 30/30';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e50-mm-30-40.jpeg' where brand = 'MVM' and article = 'E50 MM 30/40';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e50-mm-35-35.jpeg' where brand = 'MVM' and article = 'E50 MM 35/35';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e50-mm-40-40.jpeg' where brand = 'MVM' and article = 'E50 MM 40/40';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e50-n-30-30.jpeg' where brand = 'MVM' and article = 'E50 N 30/30';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e50-n-35-35.jpeg' where brand = 'MVM' and article = 'E50 N 35/35';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e8-ab.png' where brand = 'MVM' and article = 'E8 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e8-bn-sbn.png' where brand = 'MVM' and article = 'E8 BN/SBN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e8-mc.png' where brand = 'MVM' and article = 'E8 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e8-sn-cp.png' where brand = 'MVM' and article = 'E8 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e8a-black.png' where brand = 'MVM' and article = 'E8a BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e8a-ma.png' where brand = 'MVM' and article = 'E8a MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e9-ab.png' where brand = 'MVM' and article = 'E9 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e9-macc.png' where brand = 'MVM' and article = 'E9 MACC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e9-pcf.png' where brand = 'MVM' and article = 'E9 PCF';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/e9-sn-cp.png' where brand = 'MVM' and article = 'E9 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/hb-100e-ab.jpeg' where brand = 'MVM' and article = 'HB-100E AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/hb-100e-black.jpeg' where brand = 'MVM' and article = 'HB-100E BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/hb-100e-ma.jpeg' where brand = 'MVM' and article = 'HB-100E MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/hb-100e-mn.jpeg' where brand = 'MVM' and article = 'HB-100E MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/hb-100e-sc.jpeg' where brand = 'MVM' and article = 'HB-100E SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-100-ab.png' where brand = 'MVM' and article = 'HE-100 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-100-black.png' where brand = 'MVM' and article = 'HE-100 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-100-cp.png' where brand = 'MVM' and article = 'HE-100 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-100-ma.png' where brand = 'MVM' and article = 'HE-100 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-100-pn.png' where brand = 'MVM' and article = 'HE-100 PN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-120-ab.png' where brand = 'MVM' and article = 'HE-120 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-120-cp.png' where brand = 'MVM' and article = 'HE-120 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-120-ma.png' where brand = 'MVM' and article = 'HE-120 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-120-pcf.png' where brand = 'MVM' and article = 'HE-120 PCF';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/he-120-pn.png' where brand = 'MVM' and article = 'HE-120 PN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z30-k40-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z30/K40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z35-k35-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z35/K35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z35-k45-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z35/K45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z40-k30-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z40/K30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z40-k40-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z40/K40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z40-k50-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z40/K50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z45-k35-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z45/K35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z45-k45-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z45/K45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd15-n-z50-k50-5k.jpg' where brand = 'MVM' and article = 'KD15 N Z50/K50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-mm-z30-k30-5k.jpeg' where brand = 'MVM' and article = 'KD6PS MM Z30/K30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-mm-z35-k35-5k.jpeg' where brand = 'MVM' and article = 'KD6PS MM Z35/K35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z30-k30-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z30/K30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z35-k35-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z35/K35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z40-k30-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z40/K30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z40-k40-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z40/K40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z45-k35-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z45/K35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z45-k45-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z45/K45 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z50-k40-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z50/K40 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z50-k50-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z50/K50 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z55-k35-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z55/K35 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/kd6ps-n-z60-k30-5k.jpeg' where brand = 'MVM' and article = 'KD6PS N Z60/K30 5K';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ke50-mm-z30-k30.jpeg' where brand = 'MVM' and article = 'KE50 MM Z30/K30';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ke50-mm-z35-k35.jpeg' where brand = 'MVM' and article = 'KE50 MM Z35/K35';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ke50-mm-z40-k40.jpeg' where brand = 'MVM' and article = 'KE50 MM Z40/K40';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ke50-n-z30-k30.jpeg' where brand = 'MVM' and article = 'KE50 N Z30/K30';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ke50-n-z35-k35.jpeg' where brand = 'MVM' and article = 'KE50 N Z35/K35';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-127-sn.png' where brand = 'MVM' and article = 'M-127 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-134-sn.png' where brand = 'MVM' and article = 'M-134 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-134l-sn.png' where brand = 'MVM' and article = 'M-134L SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-135-black.png' where brand = 'MVM' and article = 'M-135 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-135-sn.png' where brand = 'MVM' and article = 'M-135 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-2054-ab.png' where brand = 'MVM' and article = 'M-2054 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-2054-sn.png' where brand = 'MVM' and article = 'M-2054 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-24-ab.jpg' where brand = 'MVM' and article = 'M-24 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-24-black.jpg' where brand = 'MVM' and article = 'M-24 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-24-ma.jpg' where brand = 'MVM' and article = 'M-24 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-24-mc.jpg' where brand = 'MVM' and article = 'M-24 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-24-sn.jpg' where brand = 'MVM' and article = 'M-24 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-25-black.png' where brand = 'MVM' and article = 'M-25 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-25-ss.png' where brand = 'MVM' and article = 'M-25 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-28-ss.png' where brand = 'MVM' and article = 'M-28 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-30-ab.png' where brand = 'MVM' and article = 'M-30 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-30-black.png' where brand = 'MVM' and article = 'M-30 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-30-sn.png' where brand = 'MVM' and article = 'M-30 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-3530-db.png' where brand = 'MVM' and article = 'M-3530 DB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-3530-gray.png' where brand = 'MVM' and article = 'M-3530 GRAY';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-3530-white.png' where brand = 'MVM' and article = 'M-3530 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-37-black.png' where brand = 'MVM' and article = 'M-37 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-37-ma.png' where brand = 'MVM' and article = 'M-37 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-37-mc.png' where brand = 'MVM' and article = 'M-37 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38-ab.png' where brand = 'MVM' and article = 'M-38 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38-ma.png' where brand = 'MVM' and article = 'M-38 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38-sn.png' where brand = 'MVM' and article = 'M-38 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38-white.png' where brand = 'MVM' and article = 'M-38 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38l-black.png' where brand = 'MVM' and article = 'M-38L BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38l-ma.png' where brand = 'MVM' and article = 'M-38L MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38l-sn.png' where brand = 'MVM' and article = 'M-38L SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-38l-white.png' where brand = 'MVM' and article = 'M-38L WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-39-black.png' where brand = 'MVM' and article = 'M-39 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-39-ma.png' where brand = 'MVM' and article = 'M-39 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-39-mc.png' where brand = 'MVM' and article = 'M-39 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-40-ab.png' where brand = 'MVM' and article = 'M-40 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-40-black.png' where brand = 'MVM' and article = 'M-40 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-40-ma.png' where brand = 'MVM' and article = 'M-40 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-40-sn.png' where brand = 'MVM' and article = 'M-40 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-4011-db.png' where brand = 'MVM' and article = 'M-4011 DB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-4011-gray.png' where brand = 'MVM' and article = 'M-4011 GRAY';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-4011-white.png' where brand = 'MVM' and article = 'M-4011 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-4012-t.jpeg' where brand = 'MVM' and article = 'M-4012 T';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-4013-t.jpeg' where brand = 'MVM' and article = 'M-4013 T';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-ab.png' where brand = 'MVM' and article = 'M-42L AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-black.png' where brand = 'MVM' and article = 'M-42L BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-ma.png' where brand = 'MVM' and article = 'M-42L MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-mc.png' where brand = 'MVM' and article = 'M-42L MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-sb.png' where brand = 'MVM' and article = 'M-42L SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-sn.png' where brand = 'MVM' and article = 'M-42L SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-42l-white.png' where brand = 'MVM' and article = 'M-42L WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-43-t.png' where brand = 'MVM' and article = 'M-43 T';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-44-t.png' where brand = 'MVM' and article = 'M-44 T';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-47-ab.png' where brand = 'MVM' and article = 'M-47 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-47-black.png' where brand = 'MVM' and article = 'M-47 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-47-sn.png' where brand = 'MVM' and article = 'M-47 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-62-sn.png' where brand = 'MVM' and article = 'M-62 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-72c-ab.png' where brand = 'MVM' and article = 'M-72C AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-72c-sn.png' where brand = 'MVM' and article = 'M-72C SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-75-black.png' where brand = 'MVM' and article = 'M-75 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/m-75-cp.png' where brand = 'MVM' and article = 'M-75 CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mb-100-sb.png' where brand = 'MVM' and article = 'MB-100 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mb-100-sn.png' where brand = 'MVM' and article = 'MB-100 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/md-1000l-sn.png' where brand = 'MVM' and article = 'MD-1000L SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/md-1000r-sn.png' where brand = 'MVM' and article = 'MD-1000R SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mg-2056-black.png' where brand = 'MVM' and article = 'MG-2056 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mg-2056-ma.png' where brand = 'MVM' and article = 'MG-2056 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mg-2056-sn.png' where brand = 'MVM' and article = 'MG-2056 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mg-2056c-black.png' where brand = 'MVM' and article = 'MG-2056C BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/mg-2056c-sn.png' where brand = 'MVM' and article = 'MG-2056C SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-100-ma.png' where brand = 'MVM' and article = 'P-100 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-100-pb.png' where brand = 'MVM' and article = 'P-100 PB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-100-sn.png' where brand = 'MVM' and article = 'P-100 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056-black.png' where brand = 'MVM' and article = 'P-2056 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056-ma.png' where brand = 'MVM' and article = 'P-2056 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056-sn.png' where brand = 'MVM' and article = 'P-2056 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056c-ab.png' where brand = 'MVM' and article = 'P-2056C AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056c-black.png' where brand = 'MVM' and article = 'P-2056C BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056c-ma.png' where brand = 'MVM' and article = 'P-2056C MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p-2056c-sn.png' where brand = 'MVM' and article = 'P-2056C SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e30-30-sb.png' where brand = 'MVM' and article = 'P6E30/30 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e30-30-sn.png' where brand = 'MVM' and article = 'P6E30/30 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e30-30t-sb.png' where brand = 'MVM' and article = 'P6E30/30T SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e30-30t-sn.png' where brand = 'MVM' and article = 'P6E30/30T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e35-35-sb.png' where brand = 'MVM' and article = 'P6E35/35 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e35-35-sn.png' where brand = 'MVM' and article = 'P6E35/35 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e35-35t-sb.png' where brand = 'MVM' and article = 'P6E35/35T SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e35-35t-sn.png' where brand = 'MVM' and article = 'P6E35/35T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6e40-40-sn.png' where brand = 'MVM' and article = 'P6E40/40 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p30-30-sb.png' where brand = 'MVM' and article = 'P6P30/30 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p30-30-sn.png' where brand = 'MVM' and article = 'P6P30/30 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p30-30t-sb.png' where brand = 'MVM' and article = 'P6P30/30T SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p30-30t-sn.png' where brand = 'MVM' and article = 'P6P30/30T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p30-40-sb.png' where brand = 'MVM' and article = 'P6P30/40 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p30-40-sn.png' where brand = 'MVM' and article = 'P6P30/40 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-35-sb.png' where brand = 'MVM' and article = 'P6P35/35 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-35-sn.png' where brand = 'MVM' and article = 'P6P35/35 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-35t-sb.png' where brand = 'MVM' and article = 'P6P35/35T SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-35t-sn.png' where brand = 'MVM' and article = 'P6P35/35T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-45-sn.png' where brand = 'MVM' and article = 'P6P35/45 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-45t-sn.png' where brand = 'MVM' and article = 'P6P35/45T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35-55-sn.png' where brand = 'MVM' and article = 'P6P35/55 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35t-45-sn.png' where brand = 'MVM' and article = 'P6P35T/45 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p35t-55-sn.png' where brand = 'MVM' and article = 'P6P35T/55 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p40-40-sn.png' where brand = 'MVM' and article = 'P6P40/40 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p40-40t-sn.png' where brand = 'MVM' and article = 'P6P40/40T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p40t-30-sn.png' where brand = 'MVM' and article = 'P6P40T/30 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p45-45-sn.png' where brand = 'MVM' and article = 'P6P45/45 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p45-45t-sn.png' where brand = 'MVM' and article = 'P6P45/45T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p50-30-sn.png' where brand = 'MVM' and article = 'P6P50/30 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p50-40-sn.png' where brand = 'MVM' and article = 'P6P50/40 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p50-40t-sn.png' where brand = 'MVM' and article = 'P6P50/40T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p50-50-sn.png' where brand = 'MVM' and article = 'P6P50/50 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/p6p50-50t-sn.png' where brand = 'MVM' and article = 'P6P50/50T SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1101-ss.png' where brand = 'MVM' and article = 'S-1101 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1108-ss.png' where brand = 'MVM' and article = 'S-1108 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1108-72-ss.png' where brand = 'MVM' and article = 'S-1108-72 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1108-85-ss.png' where brand = 'MVM' and article = 'S-1108-85 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1115-ss.png' where brand = 'MVM' and article = 'S-1115 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1119-ss.png' where brand = 'MVM' and article = 'S-1119 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1135-black.png' where brand = 'MVM' and article = 'S-1135 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1135-ss.png' where brand = 'MVM' and article = 'S-1135 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1136-black.png' where brand = 'MVM' and article = 'S-1136 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1136-ss.png' where brand = 'MVM' and article = 'S-1136 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1136-85-ss.png' where brand = 'MVM' and article = 'S-1136-85 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1137-black.png' where brand = 'MVM' and article = 'S-1137 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s-1137-ss.png' where brand = 'MVM' and article = 'S-1137 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/s101-200-ss.png' where brand = 'MVM' and article = 'S101-200 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sd-100.png' where brand = 'MVM' and article = 'SD-100';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sdh-1-sn-cp.png' where brand = 'MVM' and article = 'SDH-1 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sdh-2-black.png' where brand = 'MVM' and article = 'SDH-2 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sdh-2-ma.png' where brand = 'MVM' and article = 'SDH-2 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sdh-2-sn-cp.png' where brand = 'MVM' and article = 'SDH-2 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sdh-2-white.png' where brand = 'MVM' and article = 'SDH-2 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sh-100-black.png' where brand = 'MVM' and article = 'SH-100 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sh-100-sn.png' where brand = 'MVM' and article = 'SH-100 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sh-100l-black.png' where brand = 'MVM' and article = 'SH-100L BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sh-100l-sn.png' where brand = 'MVM' and article = 'SH-100L SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sh-100r-black.png' where brand = 'MVM' and article = 'SH-100R BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sh-100r-sn.png' where brand = 'MVM' and article = 'SH-100R SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/shb-100-black.png' where brand = 'MVM' and article = 'SHB-100 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/shb-100-sn.png' where brand = 'MVM' and article = 'SHB-100 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/smg-2056-black.png' where brand = 'MVM' and article = 'SMG-2056 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/smg-2056-sn.png' where brand = 'MVM' and article = 'SMG-2056 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/smg-2056c-black.png' where brand = 'MVM' and article = 'SMG-2056C BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/smg-2056c-sn.png' where brand = 'MVM' and article = 'SMG-2056C SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sp-2056-black.png' where brand = 'MVM' and article = 'SP-2056 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sp-2056-sn.png' where brand = 'MVM' and article = 'SP-2056 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sp-2056c-black.png' where brand = 'MVM' and article = 'SP-2056C BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/sp-2056c-sn.png' where brand = 'MVM' and article = 'SP-2056C SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ss-100-black.png' where brand = 'MVM' and article = 'SS-100 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ss-100-ss.png' where brand = 'MVM' and article = 'SS-100 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ss-100l-ss.png' where brand = 'MVM' and article = 'SS-100L SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ss-100r-ss.png' where brand = 'MVM' and article = 'SS-100R SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/ss-120-ss.png' where brand = 'MVM' and article = 'SS-120 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t1-ma.png' where brand = 'MVM' and article = 'T1 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t11-ss.png' where brand = 'MVM' and article = 'T11 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t12-black.png' where brand = 'MVM' and article = 'T12 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t12-ss.png' where brand = 'MVM' and article = 'T12 SS';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t16-black.png' where brand = 'MVM' and article = 'T16 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t19-black.png' where brand = 'MVM' and article = 'T19 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t19-ma.png' where brand = 'MVM' and article = 'T19 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t19-mc.png' where brand = 'MVM' and article = 'T19 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t19-mn.png' where brand = 'MVM' and article = 'T19 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t19-sb.jpeg' where brand = 'MVM' and article = 'T19 SB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t19-sn.png' where brand = 'MVM' and article = 'T19 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t2-ab.png' where brand = 'MVM' and article = 'T2 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t2-sn-cp.png' where brand = 'MVM' and article = 'T2 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t20-black.png' where brand = 'MVM' and article = 'T20 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t20-ma.png' where brand = 'MVM' and article = 'T20 MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t20-mc.png' where brand = 'MVM' and article = 'T20 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t20-mn.jpeg' where brand = 'MVM' and article = 'T20 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t20-sn.png' where brand = 'MVM' and article = 'T20 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t3-ab.png' where brand = 'MVM' and article = 'T3 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t3-macc.png' where brand = 'MVM' and article = 'T3 MACC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t3-pcf.png' where brand = 'MVM' and article = 'T3 PCF';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t3-sn-cp.png' where brand = 'MVM' and article = 'T3 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t4-black.png' where brand = 'MVM' and article = 'T4 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t4-mc.png' where brand = 'MVM' and article = 'T4 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t4-moc.png' where brand = 'MVM' and article = 'T4 MOC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t7-ab.png' where brand = 'MVM' and article = 'T7 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t7-bn-sbn.png' where brand = 'MVM' and article = 'T7 BN/SBN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t7-mc.png' where brand = 'MVM' and article = 'T7 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t7-sn-cp.png' where brand = 'MVM' and article = 'T7 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t7a-black.png' where brand = 'MVM' and article = 'T7a BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t7a-ma.png' where brand = 'MVM' and article = 'T7a MA';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t8-ab.png' where brand = 'MVM' and article = 'T8 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/t8-sn-cp.png' where brand = 'MVM' and article = 'T8 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/wc-100-ab.png' where brand = 'MVM' and article = 'WC-100 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/wc-100-sn.png' where brand = 'MVM' and article = 'WC-100 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1210-sn-cp.png' where brand = 'MVM' and article = 'Z-1210 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1220-sn-cp.png' where brand = 'MVM' and article = 'Z-1220 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1220-e20-black.png' where brand = 'MVM' and article = 'Z-1220/E20 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1220-e20-sn.png' where brand = 'MVM' and article = 'Z-1220/E20 SN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1259-ab.png' where brand = 'MVM' and article = 'Z-1259 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1259-sn-cp.png' where brand = 'MVM' and article = 'Z-1259 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1290-sn-cp.png' where brand = 'MVM' and article = 'Z-1290 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1311-macc.png' where brand = 'MVM' and article = 'Z-1311 MACC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1312-ab.png' where brand = 'MVM' and article = 'Z-1312 AB';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1312-macc.png' where brand = 'MVM' and article = 'Z-1312 MACC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1313-macc.png' where brand = 'MVM' and article = 'Z-1313 MACC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1313-pcf.png' where brand = 'MVM' and article = 'Z-1313 PCF';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1313-sn-cp.png' where brand = 'MVM' and article = 'Z-1313 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1319-sn-cp.png' where brand = 'MVM' and article = 'Z-1319 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1320-e20-black.png' where brand = 'MVM' and article = 'Z-1320/E20 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1320-e20-bn-sbn.png' where brand = 'MVM' and article = 'Z-1320/E20 BN/SBN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1325-bn-sbn.png' where brand = 'MVM' and article = 'Z-1325 BN/SBN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1325-sn-cp.png' where brand = 'MVM' and article = 'Z-1325 SN/CP';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1355-bn-sbn.png' where brand = 'MVM' and article = 'Z-1355 BN/SBN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1807-black.png' where brand = 'MVM' and article = 'Z-1807 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1807-sc.png' where brand = 'MVM' and article = 'Z-1807 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1808-black.png' where brand = 'MVM' and article = 'Z-1808 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1808-mn.png' where brand = 'MVM' and article = 'Z-1808 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1809-mn.png' where brand = 'MVM' and article = 'Z-1809 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1809-sc.png' where brand = 'MVM' and article = 'Z-1809 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1809-e20-mn.png' where brand = 'MVM' and article = 'Z-1809/E20 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1810-black.png' where brand = 'MVM' and article = 'Z-1810 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1810-mn.png' where brand = 'MVM' and article = 'Z-1810 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1810-sc.png' where brand = 'MVM' and article = 'Z-1810 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1811-e20-black.png' where brand = 'MVM' and article = 'Z-1811/E20 Black';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1811-e20-mn.png' where brand = 'MVM' and article = 'Z-1811/E20 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1812-black.png' where brand = 'MVM' and article = 'Z-1812 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1812-mc.png' where brand = 'MVM' and article = 'Z-1812 MC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1813-black.png' where brand = 'MVM' and article = 'Z-1813 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1813-mn.png' where brand = 'MVM' and article = 'Z-1813 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1813-sc.png' where brand = 'MVM' and article = 'Z-1813 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1814-black.png' where brand = 'MVM' and article = 'Z-1814 BLACK';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1814-mn.png' where brand = 'MVM' and article = 'Z-1814 MN';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/z-1814-sc.png' where brand = 'MVM' and article = 'Z-1814 SC';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/dekoratyvna-vstavka-z-1440-white.png' where brand = 'MVM' and article = 'Декоративна вставка Z-1440 WHITE';
update public.hardware_tariff_prices set photo = '/photos/furnitura/mvm/zavisy-solo.png' where brand = 'MVM' and article = 'ЗАВІСИ SOLO';
